name = "hlspresso"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
send_metrics = false

[[kv_namespaces]]
binding = "hlspresso"
id = "35a88731b6de4bcfb56085ab305143d5"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true